name: ci

on:
  push:
  schedule:
    # At 10:25 on every Wednesday
    - cron: "25 10 * * 3"

jobs:
  with-jest-swc:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: with-jest-swc
    strategy:
      matrix:
        node-version: ["16", "18", "20"]
        package-manager: ["yarn", "npm"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - run: ${{ matrix.package-manager }} install
      - run: ${{ matrix.package-manager }} run test

  with-jest-ts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: with-jest-ts
    strategy:
      matrix:
        node-version: ["16", "18", "20"]
        package-manager: ["yarn", "npm"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - run: ${{ matrix.package-manager }} install
      - run: ${{ matrix.package-manager }} run test

  with-nextjs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: with-nextjs
    strategy:
      matrix:
        node-version: ["16", "18", "20"]
        package-manager: ["yarn", "npm"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - run: ${{ matrix.package-manager }} install
      - run: ${{ matrix.package-manager }} run build
      - run: ${{ matrix.package-manager }} run test

  with-vite:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: with-vite
    strategy:
      matrix:
        node-version: ["16", "18", "20"]
        package-manager: ["yarn", "npm"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - run: ${{ matrix.package-manager }} install
      - run: ${{ matrix.package-manager }} run build
